### ISSUE TITLE
Quantile of multiple series?

### ISSUE THREAD

**Issue by TheDan64** [ritchie46/polars#109]
Suppose I have n series in a frame, each of the same type, f64, and I'd like to efficiently find a quantile of all their data. Is this possible?

I saw that you can do a quantile after a groupby, but I don't think groupby is what I need to do. I suppose I could append all of the series together, but I wasn't sure how efficient that'd be, and then I'd still be required to do a groupby prior to calling quantile which seems incorrect. Maybe a quantile method could be added for Series?

**Comment by ritchie46** [comment]
Those are easy requests. :) 

Added quantile aggregation to `ChunkedArrays` in b5c3dce457e1c9a15cc3746e8ae0b1d854cb937b. Because the quantile value is typed it isn't available on `Series`. If you know the type you can unpack them with `column.f64().unwrap().quantile(0.3)`. If you don't you could pattern match or cast.

**Comment by TheDan64** [comment]
Wow, thank you! I appreciate your quick response and impl!
