### ISSUE TITLE
LargeUtf8 usage

### ISSUE THREAD

**Issue by Posnet** [ritchie46/polars#320]
Hi,
I was wondering if you could explain the reasoning behind casting utf8/strings to the Arrow LargeString/LargeUtf8 type?

It seems like an inefficient use of memory for the default to use it, when I would think the need for cells larger than 2GB is rare.
It is also not supported by the JavaScript version of Arrow, which means there would need to be a conversion step if the output of polars is to be sent to a js frontend.

Also, would you be open to a pull request to add support for the regular string type and to change the default to it?

**Comment by ritchie46** [comment]
Hi Posnet, The bounds of  `Utf8Type` are quite easily reached. The 2GB limit is over the whole array, not over a cell. In `Utf8Type` the offsets of the start of the string bytes is encoded by a signed 32 bit integer, hence the 2GB indeed. With the standard `Utf8Type` Polars was unable to run the 50GB benchmark of db-benchmark, that's why I made the `LargeUtf8` the default.

Ideally, I'd like to support both. It would however be quite a refactor to do so. I would be open to a PR on supporting both `Utf8/ LargeUtf8` (also as `Utf8 `default),

**Comment by Posnet** [comment]
Apologies, you are right its per array.
I am still getting a handle on how chunked arrays map to arrow data types. Would the limit apply to each chunk independently as they map to array ArrayRefs?

**Comment by ritchie46** [comment]
Yes, they do. However the limits are not checked in the various algorithm implementations. So using a `Utf8` of multiple chunks will be able to exceed the 2GB limit. But it will likely be aggregated to a single chunk by an operation used by Polars. The ChunkedArray abstraction merely exists to have very cheap append operation. Polars favors however single chunked data, so it will rechunk as soon as possible.

**Comment by Posnet** [comment]
Thank you for the explanation. I'll close this issue and rethink my specific use case (which is proxying results from polars to a grafana frontend).

**Comment by ritchie46** [comment]
@Posnet, You could still cast from a `LargeUtf8` to `Utf8` just before you inject data to `arrowjs`.
